apiVersion: apps/v1
kind: Deployment
metadata:
  name: knoxweather-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: knoxweather
  template:
    metadata:
      labels:
        app: knoxweather
    spec:
      containers:
        - name: knoxweather-container
          image: 'rupeshs11/knoxweather:13'
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
