apiVersion: v1
kind: Service
metadata:
  name: knoxweather-svc
spec:
  selector: { app: knoxweather }
  ports: [{ port: 80, targetPort: 5000 }]
  type: LoadBalancer # AWS will automatically provision a Load Balancer for your app
